on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        with:
        id: hello
          who-to-greet: "World"
      - run:
          echo "Time: ${{ steps.hello.outputs.time}}"